# Generated by Django 6.0.1 on 2026-01-17 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('city_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('location_key', models.CharField(max_length=50)),
                ('search_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
